package main

var (
	slaveCpusPercent              = newSlaveMetric("cpus_percent", "CPU used in percent.")
	slaveCpusTotal                = newSlaveMetric("cpus_total", "Total CPU count.")
	slaveCpusUsed                 = newSlaveMetric("cpus_used", "CPUs allocated to tasks.")
	slaveDiskPercent              = newSlaveMetric("disk_percent", "Disk usage in percent.")
	slaveDiskTotal                = newSlaveMetric("disk_total", "Disk available.")
	slaveDiskUsed                 = newSlaveMetric("disk_used", "Disk used.")
	slaveExecutorsRegistering     = newSlaveMetric("executors_registering", "Executors registering count.")
	slaveExecutorsRunning         = newSlaveMetric("executors_running", "Executors running count.")
	slaveExecutorsTerminated      = newSlaveMetric("executors_terminated", "Executors terminated count.")
	slaveExecutorsTerminating     = newSlaveMetric("executors_terminating", "Executors terminating count.")
	slaveFrameworksActive         = newSlaveMetric("frameworks_active", "Number of active frameworks.")
	slaveInvalidFrameworkMessages = newSlaveMetric("invalid_framework_messages", "Invalid framework message count.")
	slaveInvalidStatusUpdates     = newSlaveMetric("invalid_status_updates", "Invalid status update count.")
	slaveMemPercent               = newSlaveMetric("mem_percent", "Memory usage in percent.")
	slaveMemTotal                 = newSlaveMetric("mem_total", "Memory total available.")
	slaveMemUsed                  = newSlaveMetric("mem_used", "Memory total used.")
	slaveRecoveryErrors           = newSlaveMetric("recovery_errors", "Recovery error count.")
	slaveRegistered               = newSlaveMetric("registered", "Register count.")
	slaveTasksFailed              = newSlaveMetric("tasks_failed", "Number of tasks failed.")
	slaveTasksFinished            = newSlaveMetric("tasks_finished", "Number of tasks finished.")
	slaveTasksKilled              = newSlaveMetric("tasks_killed", "Number of tasks killed.")
	slaveTasksLost                = newSlaveMetric("tasks_lost", "Number of tasks lost.")
	slaveTasksRunning             = newSlaveMetric("tasks_running", "Number of tasks running.")
	slaveTasksStaging             = newSlaveMetric("tasks_staging", "Number of tasks staging.")
	slaveTasksStarting            = newSlaveMetric("tasks_starting", "Number of tasks starting.")
	slaveUptimeSecs               = newSlaveMetric("uptime_secs", "Slave uptime in seconds.")
	slaveValidFrameworkMessages   = newSlaveMetric("valid_framework_messages", "Valid framework message count.")
	slaveValidStatusUpdates       = newSlaveMetric("valid_status_updates", "Valid status updates count.")

	sysCpusTotal     = newSystemMetric("cpus_total", "Total CPU count.")
	sysLoad15min     = newSystemMetric("load_15min", "System load 15 minute.")
	sysLoad1min      = newSystemMetric("load_1min", "System load 1 minute.")
	sysLoad5min      = newSystemMetric("load_5min", "System load 5 minute.")
	sysMemFreeBytes  = newSystemMetric("mem_free_bytes", "Total memory free in bytes.")
	sysMemTotalBytes = newSystemMetric("mem_total_bytes", "Total memory used in bytes.")

	taskCpuLimitDesc       = newTaskMetric("cpus_limit", "Fractional CPU limit")
	taskCpuNrPeriodsDesc   = newTaskMetric("cpus_nr_periods", "Cumulative CPU periods.")
	taskCpuNrThrottledDesc = newTaskMetric("cpus_nr_throttled", "Cumulative throttled CPU periods.")
	taskCpuSysDesc         = newTaskMetric("cpus_system_time_secs", "Cumulative system CPU time in seconds.")
	taskCpuThrottledDesc   = newTaskMetric("cpus_throttled_time_secs", "Cumulative throttled CPU time in seconds.")
	taskCpuUsrDesc         = newTaskMetric("cpu_user_time_secs", "Cumulative user CPU time in seconds.")
	taskDiskLimitBytes     = newTaskMetric("disk_limit_bytes", "Task disk quota.")
	taskDiskUsedBytes      = newTaskMetric("disk_used_bytes", "Task disk usage.")
	taskMemAnonDesc        = newTaskMetric("memory_anon_bytes", "Task memory anonymous usage in bytes.")
	taskMemFileDesc        = newTaskMetric("memory_file_bytes", "Task memory file usage in bytes.")
	taskMemMappedDesc      = newTaskMetric("memory_mapped_bytes", "Task memory mapped usage in bytes.")
	taskMemLimitDesc       = newTaskMetric("memory_limit_bytes", "Task memory limit in bytes.")
	taskMemRssDesc         = newTaskMetric("memory_rss_bytes", "Task memory RSS usage in bytes.")
	taskNetRxBytes         = newTaskMetric("net_rx_bytes", "Network received bytes.")
	taskNetRxDropped       = newTaskMetric("net_rx_dropped", "Network received packets dropped.")
	taskNetRxErrors        = newTaskMetric("net_rx_errors", "Network received packet errors.")
	taskNetRxPackets       = newTaskMetric("net_rx_packets", "Network received packets.")
	taskNetTxBytes         = newTaskMetric("net_tx_bytes", "Network sent bytes.")
	taskNetTxDropped       = newTaskMetric("net_tx_dropped", "Network sent packets dropped.")
	taskNetTxErrors        = newTaskMetric("net_tx_errors", "Network sent packets ererors.")
	taskNetTxPackets       = newTaskMetric("net_tx_packets", "Network sent packets.")
)
